"""empty message

Revision ID: d2427d186a63
Revises: 
Create Date: 2022-04-19 20:30:54.180017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2427d186a63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('box_name', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=2), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('out', sa.Boolean(), nullable=True),
    sa.Column('needs_cleaning', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(length=128), nullable=True),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=96), nullable=True),
    sa.Column('password_hash', sa.String(length=102), nullable=True),
    sa.Column('sciper', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sciper')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('borrowing_date', sa.Date(), nullable=True),
    sa.Column('borrowed_quantity', sa.Integer(), nullable=True),
    sa.Column('borrowing_description', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowing_timestamp'), 'borrowing', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrowing_timestamp'), table_name='borrowing')
    op.drop_table('borrowing')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
