"""removes images and adds acl to items

Revision ID: e4d0e5ad7f0d
Revises: fdc8272599cd
Create Date: 2022-06-16 21:57:11.736647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d0e5ad7f0d'
down_revision = 'fdc8272599cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('access_control_list', sa.PickleType(), nullable=True))
    op.create_index(op.f('ix_item_access_control_list'), 'item', ['access_control_list'], unique=False)
    op.drop_column('item', 'image')
    op.create_index(op.f('ix_user_roles'), 'user', ['roles'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles'), table_name='user')
    op.add_column('item', sa.Column('image', sa.BLOB(), nullable=True))
    op.drop_index(op.f('ix_item_access_control_list'), table_name='item')
    op.drop_column('item', 'access_control_list')
    # ### end Alembic commands ###
